# Generated by Django 3.2.7 on 2021-10-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRestaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='favorite',
            field=models.ManyToManyField(blank=True, through='appRestaurante.Detail_Favoritos', to='appRestaurante.Recipe'),
        ),
    ]
